# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b094c02c6ad9896aec7fc6c43e2ef7cf"
application_url = "https://larry-jerry-ds-park.trycloudflare.com"
embedded = true
name = "practice-app"
handle = "practice-app-110"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://larry-jerry-ds-park.trycloudflare.com/auth/callback",
  "https://larry-jerry-ds-park.trycloudflare.com/auth/shopify/callback",
  "https://larry-jerry-ds-park.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "anuj-testing-app.myshopify.com"
automatically_update_urls_on_dev = true
