# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "342d021a78972df793cd2a9f2acd358b"
application_url = "https://him-calculators-became-tournaments.trycloudflare.com"
embedded = true
name = "practice-app-1"
handle = "practice-app-111"

[build]
include_config_on_deploy = true
dev_store_url = "anuj-testing-app.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://him-calculators-became-tournaments.trycloudflare.com/auth/callback",
  "https://him-calculators-became-tournaments.trycloudflare.com/auth/shopify/callback",
  "https://him-calculators-became-tournaments.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
